version: '3.5'

services:

  backend:
    #: ddeeh/springci
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    command: ["java", "-jar", "./dockerci-0.0.1-SNAPSHOT.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres

  frontend:
    build:
      context: https://github.com/andreedd/ReactCI.git
      dockerfile: Dockerfile.prod
    working_dir: /app
    ports:
      - "3000:80"
    stdin_open: true
    depends_on:
      - backend

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
    depends_on:
      - db

#  watchtower:
#    image: containrrr/watchtower
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    container_name: watchtower

volumes:
  pgdata: